[13.0][FIX] sale_report_delivered: The weight and volume of returns is increasing the total instead of decreasing it
OCA/sale-reporting pull request #151
Opened 2022-05-11 09:07 UTC by CarlosRoca13

cc @Tecnativa TT36635

please @carlosdauden @sergio-teruel review this

2022-05-11 11:17 UTC, carlosdauden requested changes

2022-05-11 11:17 UTC, carlosdauden commented on sale_report_delivered/reports/sale_report.py
> +            ) * sm.product_uom_qty / u.factor * u2.factor as volume,
Replace PR changes by:
            sum(signed_qty * sub.weight) as weight,
            sum(signed_qty * sub.volume) as volume,
in
https://github.com/OCA/sale-reporting/pull/151/files#diff-0ea6a8e310c8aedd7d64cd2e9dc00f983471b36f5254176023547b7f678bc2eeR87-R88

2022-05-11 11:24 UTC, carlosdauden approved these changes

2022-05-18 14:00 UTC, sergio-teruel approved these changes

2022-05-18 14:02 UTC, pedrobaeza commented
/ocabot merge patch

2022-05-18 14:06 UTC, merged