[MIG] sale_order_report_product_image: Migration to 17.0
OCA/sale-reporting pull request #283
Opened 2024-09-19 01:20 UTC by JoseIbarraHdz

- update version to 17.0.1.0.0

2024-09-19 17:40 UTC, edy1192 commented
Functional test LGTM 👍🏼

2024-09-19 17:45 UTC, edy1192 commented
Hi @manuelregidor could you check this, please?

cc @JoseIbarraHdz

2024-09-20 08:41 UTC, manuelregidor commented
@edy1192 You need to have two commits: one for the pre-commit auto fixes and another one for the migration itself.

2024-09-24 15:36 UTC, antoniocanovas approved these changes
Functional review OK !!

2024-09-25 16:24 UTC, JoseIbarraHdz commented
Hi @manuelregidor could you check this please? There are the two commits you mentioned above.

Regards.

cc. @edy1192

2024-09-26 06:07 UTC, manuelregidor approved these changes
Technical review. LGTM

2024-09-26 06:55 UTC, pedrobaeza requested changes
There's a mix of changes in commits: some of them should be on the migration commit (like the README ones), and some on the pre-commit auto-fixes.

2024-09-26 06:55 UTC, pedrobaeza commented on pandoc-3.4-1-amd64.deb
This file shouldn't be present.

2024-10-02 16:03 UTC, JoseIbarraHdz commented
Hi @pedrobaeza I did the changes you requested, can you please check?

2024-10-02 19:43 UTC, pedrobaeza approved these changes
OK, there are still some mix of changes between commits, but for this time is enough. Please follow all the steps of the migration guide the next time for avoiding this kind of things. 

/ocabot merge nobump

2024-10-03 16:54 UTC, JoseIbarraHdz commented
Hi @pedrobaeza thanks for the approval,  I'll follow the guide steps next time, by the way, it is already merged?

Regards.

2024-10-04 06:21 UTC, pedrobaeza commented
/ocabot merge nobump

2024-10-04 06:22 UTC, pedrobaeza commented
/ocabot migration sale_order_report_product_image

2024-10-04 06:25 UTC, merged