[IMP] sale_comment_template: add partner template
OCA/sale-reporting pull request #46
Opened 2018-03-20 11:07 UTC by cubells

Add missing feature from older version: now you can assign a comment template to partner.
- Update spanish translation

cc @Tecnativa

2018-03-20 12:10 UTC, pedrobaeza requested changes
Why on sale_comment_template? It should be on `invoice_comment_template`, that is the base module.

It misses also the onchanges on partner for putting the template. If not, for what is worth this?

2018-10-16 14:24 UTC, rafaelbn commented
@cubells please, could you resolver conflict in this PR in order to get :green_apple: :green_heart: bots? Thanks!

@pedrobaeza your commnets i think were attended

2018-10-17 07:54 UTC, cubells commented
@rafaelbn all is :green_heart: now!

2018-10-17 17:16 UTC, rafaelbn approved these changes
Tested functionally in runbot :+1:

2018-10-17 17:16 UTC, rafaelbn commented
All is OK! Thanks @cubells 

Maybe README could be the new standard

2018-10-17 17:32 UTC, pedrobaeza approved these changes

2018-10-17 17:32 UTC, merged

2018-10-17 17:33 UTC, pedrobaeza commented
Please submit the same to v11