[9.0] product_brand_sale_report: New module
OCA/sale-reporting pull request #49
Opened 2018-04-03 18:11 UTC by chienandalu

Product Brand Sale Report
=========================

Adds product brand to the sale report.

Usage
=====

Go to *Sales > Reports* and filter or group by brand.

cc @Tecnativa

2018-04-03 22:23 UTC, pedrobaeza requested changes
Please add also in the search view the possibility to filter by brand `<field name="product_brand_id"/>`

2018-04-03 22:23 UTC, pedrobaeza commented on product_brand_sale_report/README.rst
> +Usage
Add installation section saying that it requires the module `product_brand` that is on ...OCA/product-attribute.

2018-04-03 22:23 UTC, pedrobaeza commented on product_brand_sale_report/__openerp__.py
> +    'summary': 'Product Brand Sale Report',
Don't put summary, as it equals to the name.

2018-04-03 22:23 UTC, pedrobaeza commented on product_brand_sale_report/__openerp__.py
> +    'name': 'Product Brand Sale Report',
`Product Brand in Sales analysis`

2018-04-10 11:09 UTC, rafaelbn approved these changes
Thanks @chienandalu :+1: 

Please add a note to indicate that in v10 v11 ... we must integrate this functionality in the main product_brand module as commented because: 

- https://github.com/OCA/product-attribute/pull/191/files#r92249387
- https://github.com/OCA/product-attribute/blob/11.0/product_brand/__manifest__.py#L19

Ping @carlosdauden

2018-04-10 12:29 UTC, chienandalu commented
@rafaelbn done

2018-04-10 12:45 UTC, carlosdauden approved these changes

2018-04-10 19:27 UTC, pedrobaeza approved these changes

2018-04-10 19:27 UTC, merged