[MIG] sale_layout_category_hide_detail: Migration to 13.0
OCA/sale-reporting pull request #76
Opened 2019-11-18 13:11 UTC by sebalix

2019-11-18 15:32 UTC, pedrobaeza requested changes
I'm missing a75e0073edf6621633b3f87f4e84e4fce65caa23 here

2019-11-18 15:32 UTC, pedrobaeza commented on sale_layout_category_hide_detail/migrations/12.0.1.0.0/pre-migration.py
> +# Copyright 2019 Tecnativa - Pedro M. Baeza
Please remove this file

2019-11-21 08:48 UTC, TDu commented on sale_layout_category_hide_detail/migrations/12.0.1.0.0/pre-migration.py
> +# Copyright 2019 Tecnativa - Pedro M. Baeza
Done

2019-11-21 10:35 UTC, TDu commented
Black seems to be weirdly configured ! Asking for lines longer than 80 char :confused:

2019-11-21 11:48 UTC, pedrobaeza commented
> Black seems to be weirdly configured ! Asking for lines longer than 80 char

Line length is no longer a requirement. We let black to decide. That's why now there's no such linter to put in red if exceeded.

2019-11-21 13:09 UTC, TDu commented
Thanks for the explanation, that line length really surprised me :)

2019-11-22 13:33 UTC, ernestotejeda approved these changes

2019-11-27 14:48 UTC, ernestotejeda commented
LGTM :+1:

2019-11-27 15:29 UTC, pedrobaeza commented
Can you please squash migrations commits together and I'll proceed to merge?

2019-11-27 15:29 UTC, pedrobaeza commented
@ernestotejeda please give a proper review, not a comment.

2019-11-27 15:54 UTC, ernestotejeda approved these changes

2019-12-30 16:04 UTC, pedrobaeza approved these changes
I have squashed myself and add also 1c7a923300d27df97f90b4f0c65b4dd5fc2d0485 that is something I have fixed for 12.0

2019-12-30 16:04 UTC, pedrobaeza commented
/ocabot merge

2019-12-30 16:40 UTC, merged