[ADD][13] sale_optional_product_section
OCA/sale-reporting pull request #81
Opened 2019-11-26 15:40 UTC by TDu

2019-11-28 08:53 UTC, i-vyshnevska approved these changes

2019-11-28 08:53 UTC, i-vyshnevska commented on sale_optional_product_section/readme/CONTRIBUTORS.rst
> +  * Thierry Ducrest
```suggestion
* Thierry Ducres <....@camptocamp.com>
```

2019-11-28 10:39 UTC, sebalix approved these changes

2020-01-03 11:29 UTC, AaronHForgeFlow approved these changes
:+1: LGTM

2020-01-03 15:44 UTC, rousseldenis requested changes

2020-01-03 15:44 UTC, rousseldenis commented on sale_optional_product_section/__manifest__.py
> +    "license": "LGPL-3",
Is it an AGPL or LPGL one ? licensing marks are opposite through the file

2021-04-13 06:19 UTC, rousseldenis commented
@TDu Could you fix this ?

2021-04-14 01:07 UTC, TDu commented
@rousseldenis I rebased and fixed the linting. I think the licence is also good now ?

2022-05-29 12:38 UTC, closed without merging